blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/nikhilbadyal/docker-py-revanced/discussions/new/choose
    about: Please ask and answer questions here.
