name: Check for new Revanced apps

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      CREATE_ISSUE:
        description: "Create GitHub issue"
        required: false
        type: boolean
        default: false

jobs:
  status_check:
    if: github.repository == 'nikhilbadyal/docker-py-revanced'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@main

      - name: setup python
        uses: actions/setup-python@main
        with:
          python-version: '3.11.5'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Status Check
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          output=$(python -m scripts.status_check)
          echo "changelog<<$EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        id: status

      - name: Update Check
        run: |
          echo "${{ steps.status.outputs.changelog }}"

      - name: Upload status file
        uses: actions/upload-artifact@main
        with:
          name: issue_body.md
          path: status.md
          if-no-files-found: error

      - name: Create Issue Action
        if: inputs.CREATE_ISSUE
        uses: nashmaniac/create-issue-action@v1.2
        with:
          title: Revanced apps Status
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{ github.repository_owner }}
          labels: 💁‍new-app
          body: ${{ steps.status.outputs.changelog }}
