name: PR Checks
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  linter-pr-check:
    uses: nikhilbadyal/ghactions/.github/workflows/python-linter.yml@main
    with:
      PYTHON_VERSION: '3.10'
  build-apk-pr-check:
    uses: ./.github/workflows/build-artifact.yml
    with:
      FILES_TO_EXPECT: 2
    secrets:
      ENVS: |
        CI_TEST=True
        ES_JAVA_OPTS: '-Xms4g -Xmx4g'
        PERSONAL_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
