name: PR Checks
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  pull_request:
    paths-ignore:
      - '*.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-apk-pr-check:
    uses: ./.github/workflows/build-artifact.yml
    with:
      CI_TEST: true
    secrets:
      ENVS: |
        CI_TEST=True
        ES_JAVA_OPTS: '-Xms4g -Xmx4g'
        PERSONAL_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
